#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$ADMIN_USER" --dbname "$ADMIN_DB" <<-EOSQL

CREATE USER ${APP_USER} WITH LOGIN SUPERUSER PASSWORD '${APP_USER_PASSWORD}';
GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO ${APP_USER};

EOSQL