name: Frontend deployment
run-name: Performs checks and deployment with latest changes
on:
  push:
    branches: [ main ]
    paths:
    - 'frontend/**'
env:
  VITE_API_URL: "${{ secrets.DOMAIN_NAME }}/api"
  VITE_CUSTOM_EMAIL: "${{ secrets.CUSTOM_EMAIL }}"
  S3_BUCKET_PATH: "s3://${{ secrets.FRONTEND_BUCKET_NAME }}/"
  CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
permissions:
  id-token: write
  contents: read
jobs:
  app-deploy:
    name: Deploy Frontend App
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v7
        with:
          node-version: '20.20.2'
          cache: 'npm'
          cache-dependency-path: ./frontend/package-lock.json

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run build
        working-directory: ./frontend
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_CI_ROLE_ARN }}
          aws-region: eu-west-1

      - name: Sync build to S3
        working-directory: ./frontend
        run: |
          aws s3 sync ./dist $S3_BUCKET_PATH --delete --exact-timestamps

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
            --paths "/*"